spring:
  datasource:
    url: jdbc:h2:mem:beerstock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
api:
  swagger:
    basePackage: "io.github.adgross.beerstock.controller"
    apiTitle: "Beer Stock API"
    apiDescription: "REST API for beer stock management"
    apiVersion: "1.0.0"
    contactName: "Ádler Jonas Gross"
    contactGithub: "https://github.com/adgross"
    contactEmail: "adlerjgross@gmail.com"
    license: "Apache 2.0"
    licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0.html"
